[http]
    host = "127.0.0.1"
    port = 8010

[datasource]
    provider = "mysql"
    host = "127.0.0.1"
    port = 3306
    database = "vblog"
    username = "root"
    password = "123456"
    debug = true

[log]
    level = "debug"

[log.console]
    enable = true
    no_color = false

[log.file]
    enable = false